version: "3.6"

services: 
  pico-static:
    build:
      context: .
      dockerfile: ./.docker/pico-static.dockerfile
    environment:
      PUBLIC_PATH: "/public"
      SERVER_PORT: 8080
    ports:
      - 8090:8080
    volumes:
      - ./public:/public
